name: Build and deploy homepage

on:
  push:
    branches:
      - main

env:
  FTP_HOST: ${{ secrets.FTP_HOST }}
  FTP_USER: ${{ secrets.FTP_USER }}
  FTP_PWD: ${{ secrets.FTP_PWD }}
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup NodeJs
        uses: actions/setup-node@v2
        with:
          node-version: '16'
      - name: Build app
        run: npm i -g yarn && yarn install && yarn build
      - run: echo ${{ secrets.FTP_HOST }}
      - name: Deploy on ftp
        uses: SamKirkland/FTP-Deploy-Action@4.2.0
        with:
          server: ${{ secrets.FTP_HOST }}
          username: ${{ secrets.FTP_USER }}
          password: ${{ secrets.FTP_PWD }}
          protocol: ftp
          port: 21
          local-dir: "./dist"
          server-dir: "./www-test"
